---

region: us-east-1
metrics:
- aws_namespace: "AWS/EC2"
  aws_dimensions: [InstanceId]
  aws_metric_name: CPUUtilization
  aws_statistics: [Average]

- aws_namespace: "AWS/EC2"
  aws_dimensions: [InstanceId]
  aws_metric_name: NetworkOut
  aws_statistics: [Average]

- aws_namespace: AWS/ELB
  aws_metric_name: HealthyHostCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Average]

- aws_namespace: AWS/ELB
  aws_metric_name: UnHealthyHostCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Average]

- aws_namespace: AWS/ELB
  aws_metric_name: RequestCount
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Sum]

- aws_namespace: AWS/ELB
  aws_metric_name: Latency
  aws_dimensions: [AvailabilityZone, LoadBalancerName]
  aws_statistics: [Average]